In [26]:
import numpy as np
# Numpy vs list
# 5(Binary)->Int 32 in numpy, and you could specify its int8 or int16
# Numpy read less bytes of memory
# No type checking in numpy
a = np.array([1,2,3,4,5]) #1 dimensional array
b = np.array([[1,2,3,4],
              [5,6,7,8]], dtype="int16")
# Dimension of array
# b.ndim
# a.shape

# Get how much memory a numpy arrays take
# Get type 
# b.dtype

# Get size
b.itemsize,a.nbytes

(2, 20)

### Accessing/Changing specific elements, rows, columns, etc

In [68]:
# Get a specific element
b[1][0]
# Get a specific row
b[0, :]
# Get a specific column
# [startIndex:endIndex:stepSize]
# b[1:, 0::1] = [9,5,6,12]

IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed

### Initializing different types of arrays

In [117]:
np.zeros((2,3))
np.ones((4,2,2), dtype="int32")
# np.full((2,2), 8, dtype="float16")
np.full_like(b.shape, 4)
np.random.rand(4,2)
np.random.random_sample(a.shape)
np.random.randint(-100, 1, size=(3,3))
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [131]:
arr = np.array([[1,2,3], [4,5,6]])
r1 = np.repeat(arr, 4, axis=0)
r1

array([[1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3],
       [4, 4, 4, 4, 5, 5, 5, 5, 6, 6, 6, 6]])

In [160]:
arrb = np.ones((5,5))
arrb[1:-1, 1:-1], arrb[2,2] = 0, 9
arrb
b = np.array([1,2,3])
a = b.copy()
b[0] = 100
b, a

(array([100,   2,   3]), array([1, 2, 3]))

### Mathematics

In [215]:
a + b
a / 2
a // 2
(a ** b).dtype
# Linear Algebra
d = np.full((2,3), 2)
e = np.full((3,2), 4)
np.matmul(d,e)

c = np.identity(3)
np.linalg.det(c)

stats = np.array([[1,2,3,21],
                  [4,5,6,10]])
np.min(stats, axis=1)  

array([1, 4])

### Reoganizing Arrays

In [216]:
before = np.array([[1,2,3,4], 
                   [5,6,7,8]])
before.reshape(1,8)
# STACKING
np.vstack([before, stats])

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 1,  2,  3, 21],
       [ 4,  5,  6, 10]])

### Load data from file

In [230]:
data = np.genfromtxt("untitled.txt", delimiter=",", dtype="int32")

(array([[0, 1, 1, 2, 2],
        [3, 3, 4, 4, 5],
        [5, 6, 6, 7, 7]], dtype=int32),
 array([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15]]))

### Boolean masking and Advancing Indexing

In [234]:
np.any(data > 5, axis=1)

array([False,  True,  True])