In [1]:
import numpy as np

In [15]:
a = np.array([1,2,3], dtype='int32')
b = np.array([4,5,6])
a.shape

(3,)

In [10]:
a.ndim

1

In [16]:
a.itemsize

4

In [29]:
c=np.array([[1,2,3,4], 
            [10,5,6,100], 
            [23,65,44,78]])
c[:, ::2]

array([[ 1,  3],
       [10,  6],
       [23, 44]])

In [49]:
v= np.array([[[1,2],[4,5]],
    [[9,8], [10,2]]])

v[0,1,1]

5

In [55]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [69]:
r = np.ones((5,13))
r[2, 6] = 0
r

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [71]:
e = np.full_like(r, 32)
e

array([[32., 32., 32., 32., 32., 32., 32., 32., 32., 32., 32., 32., 32.],
       [32., 32., 32., 32., 32., 32., 32., 32., 32., 32., 32., 32., 32.],
       [32., 32., 32., 32., 32., 32., 32., 32., 32., 32., 32., 32., 32.],
       [32., 32., 32., 32., 32., 32., 32., 32., 32., 32., 32., 32., 32.],
       [32., 32., 32., 32., 32., 32., 32., 32., 32., 32., 32., 32., 32.]])

In [84]:
np.random.rand(3,2,1,)

array([[[0.27518108],
        [0.22139828]],

       [[0.4018504 ],
        [0.72808623]],

       [[0.35921856],
        [0.93649386]]])

In [86]:
np.random.random_sample(a.shape)

array([0.99360331, 0.31161742, 0.29622278])

In [94]:
np.random.randint(13, size=(2,4))

array([[10,  3, 10,  6],
       [ 6,  3,  1,  8]])

In [101]:
arr = np.array([[1,2,3]])
r2 = np.repeat(arr,3, axis=0)
r2

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [106]:
g = np.ones((5,5))
g[1:4, 1:4], g[2,2] = 0, 9
g

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [111]:
b = np.array([1,2,3])
a = b.copy()
b[0] = 122
a

array([1, 2, 3])

In [115]:
a*201
a//2

array([0, 1, 1], dtype=int32)

In [119]:
np.cos(a)
np.tan(a)

array([ 1.55740772, -2.18503986, -0.14254654])

In [124]:
np.full((2,3),222223)
np.full_like(a, 12)
np.linalg.det(np.identity(3))


1.0

In [128]:
fdata = np.genfromtxt("untitled.txt", delimiter=',')
fdata[fdata >= 4]

array([ 4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14., 15.])

In [134]:
k = np.any(fdata > 5, axis=1)
fdata[k]

IndexError: boolean index did not match indexed array along dimension 0; dimension is 3 but corresponding boolean dimension is 5

In [152]:
fdata[((fdata > 4) & (fdata < 9)) ]

array([5., 6., 7., 8.])

In [185]:
a = np.array([[1,2,3,4,5],
              [6,7,8,9,10],
              [11,12,13,14,15],
              [16,17,18,19,20],
              [21,22,23,24,25],
              [26,27,28,29,30]
             ])
a[[0,1,2,3], [1,2,3,4]]
a[[0,4,5], 3:]

array([[ 4,  5],
       [24, 25],
       [29, 30]])

In [203]:
np.arange(1,11).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])